
name: Netifly_Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types: ['opened', 'edited', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
        name: netfly_build
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
